### PR TITLE
Add storyboard integration instructions in the README

### PR DESCRIPTION
**Pull request by 0xced**

### CODE REVIEW

**Comment by 0xced** [comment]
Ping

**Comment by friedbunny** [comment]
Swift:

```swift
lazy var window: UIWindow? = {
    return MBFingerTipWindow.init(frame: UIScreen.mainScreen().bounds)
}()
```

**Comment by 1ec5** [comment]
Thanks, and sorry for the delay.

**Comment by 1ec5** [comment]
Swift example from https://github.com/mapbox/Fingertips/pull/23#issuecomment-217245608 added in f103c989dfbf65ce3aae6d17a8fd74c57ac8581f.

**Pull request merged**
