### PR TITLE
Introduce BOOL alwaysShowFingerTip

### PR DESCRIPTION
**Pull request by junjie**

### CODE REVIEW

**Comment by incanus** [comment]
Yeah, a PR would be cool. We do have an environment variable for this but runtime support done well would be nice. 

https://github.com/mapbox/Fingertips/blob/b8bf8ff954dcaed3d06d8d8e5e70c2e92b94c1f3/MBFingerTipWindow.m#L184

**Comment by incanus** [comment]
Thanks for this! Made very slight tweaks.

**Comment by 0xced** [comment]
That new property is redundant with the `DEBUG_FINGERTIP_WINDOW` environment variable. I suggest that we should keep only one of them.

* Always displaying touches is something important, so it warrants a public property and we delete the `DEBUG_FINGERTIP_WINDOW` environment variable thing.

or

* Always displaying touches on the device is something useful for debugging purpose or niche use cases so an environment variable is enough and we delete the `alwaysShowTouches` property.

Also, maybe you have not realized that what you are achieving with the new property could have been achieved by setting the `DEBUG_FINGERTIP_WINDOW` environment variable to `YES` in the Xcode interface or like this in code:
```objc
setenv("DEBUG_FINGERTIP_WINDOW", "YES", 1);
```

**Comment by 0xced** [comment]
I created #20 with my proposal. I’d be fine with removing `DEBUG_FINGERTIP_WINDOW` too, we just don’t need the two options.

**Comment by junjie** [comment]
Re: `DEBUG_FINGERTIP_WINDOW`, that is already possible, and I believe we know about that.

Exposing a property allows the ability to turn this on/off dynamically, and to persist even when not run tethered to Xcode. Use case includes a development build for the purpose of recording screencast, showing touches and gestures without the user having to run the app from Xcode.

You mentioned `setenv`, which seems to be able to do that. I'm not familiar with that. Thanks for highlighting that.

But that seems rather obscure to most (as evident from the need to clarify that in a README, and from the two developers who contacted me and asked me to send a pull request).

Personally, I thought #20 seems counterintuitive. compared with a well-named property that all Objective-C developers know how to use and set.

**Pull request merged**
